import tokensV1 from './src/design/tokens.json';
import tokensV2 from './src/design/tokens-v2.json';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // New V2 colors (Red primary - Pro-Remorque branding, Teal secondary)
        primary: {
          DEFAULT: tokensV2.colors.primary.DEFAULT,
          50: tokensV2.colors.primary['50'],
          100: tokensV2.colors.primary['100'],
          200: tokensV2.colors.primary['200'],
          300: tokensV2.colors.primary['300'],
          400: tokensV2.colors.primary['400'],
          500: tokensV2.colors.primary['500'],
          600: tokensV2.colors.primary['600'],
          700: tokensV2.colors.primary['700'],
          800: tokensV2.colors.primary['800'],
          900: tokensV2.colors.primary['900'],
        },
        secondary: {
          DEFAULT: tokensV2.colors.secondary.DEFAULT,
          50: tokensV2.colors.secondary['50'],
          100: tokensV2.colors.secondary['100'],
          200: tokensV2.colors.secondary['200'],
          300: tokensV2.colors.secondary['300'],
          400: tokensV2.colors.secondary['400'],
          500: tokensV2.colors.secondary['500'],
          600: tokensV2.colors.secondary['600'],
          700: tokensV2.colors.secondary['700'],
          800: tokensV2.colors.secondary['800'],
          900: tokensV2.colors.secondary['900'],
        },
        // Accent color now blue (backward compatibility)
        accent: {
          DEFAULT: tokensV2.colors.accent.DEFAULT,
          50: tokensV2.colors.accent['50'],
          100: tokensV2.colors.accent['100'],
          200: tokensV2.colors.accent['200'],
          300: tokensV2.colors.accent['300'],
          400: tokensV2.colors.accent['400'],
          500: tokensV2.colors.accent['500'],
          600: tokensV2.colors.accent['600'],
          700: tokensV2.colors.accent['700'],
          800: tokensV2.colors.accent['800'],
          900: tokensV2.colors.accent['900'],
        },
        neutral: {
          DEFAULT: tokensV2.colors.neutral.DEFAULT,
          50: tokensV2.colors.neutral['50'],
          100: tokensV2.colors.neutral['100'],
          200: tokensV2.colors.neutral['200'],
          300: tokensV2.colors.neutral['300'],
          400: tokensV2.colors.neutral['400'],
          500: tokensV2.colors.neutral['500'],
          600: tokensV2.colors.neutral['600'],
          700: tokensV2.colors.neutral['700'],
          800: tokensV2.colors.neutral['800'],
          900: tokensV2.colors.neutral['900'],
        },
        success: {
          DEFAULT: tokensV2.colors.success.DEFAULT,
          50: tokensV2.colors.success['50'],
          100: tokensV2.colors.success['100'],
          200: tokensV2.colors.success['200'],
          300: tokensV2.colors.success['300'],
          400: tokensV2.colors.success['400'],
          500: tokensV2.colors.success['500'],
          600: tokensV2.colors.success['600'],
          700: tokensV2.colors.success['700'],
          800: tokensV2.colors.success['800'],
          900: tokensV2.colors.success['900'],
        },
        warning: {
          DEFAULT: tokensV2.colors.warning.DEFAULT,
          50: tokensV2.colors.warning['50'],
          100: tokensV2.colors.warning['100'],
          200: tokensV2.colors.warning['200'],
          300: tokensV2.colors.warning['300'],
          400: tokensV2.colors.warning['400'],
          500: tokensV2.colors.warning['500'],
          600: tokensV2.colors.warning['600'],
          700: tokensV2.colors.warning['700'],
          800: tokensV2.colors.warning['800'],
          900: tokensV2.colors.warning['900'],
        },
        danger: {
          DEFAULT: tokensV2.colors.danger.DEFAULT,
          50: tokensV2.colors.danger['50'],
          100: tokensV2.colors.danger['100'],
          200: tokensV2.colors.danger['200'],
          300: tokensV2.colors.danger['300'],
          400: tokensV2.colors.danger['400'],
          500: tokensV2.colors.danger['500'],
          600: tokensV2.colors.danger['600'],
          700: tokensV2.colors.danger['700'],
          800: tokensV2.colors.danger['800'],
          900: tokensV2.colors.danger['900'],
        },
        info: {
          DEFAULT: tokensV2.colors.info.DEFAULT,
          50: tokensV2.colors.info['50'],
          100: tokensV2.colors.info['100'],
          200: tokensV2.colors.info['200'],
          300: tokensV2.colors.info['300'],
          400: tokensV2.colors.info['400'],
          500: tokensV2.colors.info['500'],
          600: tokensV2.colors.info['600'],
          700: tokensV2.colors.info['700'],
          800: tokensV2.colors.info['800'],
          900: tokensV2.colors.info['900'],
        },
        // Legacy brand colors (V1 compatibility)
        brand: {
          red: tokensV1.colors.primary,
          'red-dark': tokensV1.colors['primary-700'],
          black: tokensV1.colors.secondary,
        },
      },
      spacing: {
        'xs': tokensV2.spacing.xs,
        'sm': tokensV2.spacing.sm,
        'md': tokensV2.spacing.md,
        'lg': tokensV2.spacing.lg,
        'xl': tokensV2.spacing.xl,
        '2xl': tokensV2.spacing['2xl'],
        '3xl': tokensV2.spacing['3xl'],
      },
      borderRadius: {
        'btn': tokensV2.borderRadius.btn,
        'card': tokensV2.borderRadius.card,
        'pill': tokensV2.borderRadius.pill,
        'sm': tokensV2.borderRadius.sm,
        'md': tokensV2.borderRadius.md,
        'lg': tokensV2.borderRadius.lg,
        'xl': tokensV2.borderRadius.xl,
      },
      boxShadow: {
        'card': tokensV2.shadows.card,
        'focus': tokensV2.shadows.focus,
        'button': tokensV2.shadows.button,
        'sm': tokensV2.shadows.sm,
        'md': tokensV2.shadows.md,
        'lg': tokensV2.shadows.lg,
        'xl': tokensV2.shadows.xl,
      },
      fontFamily: {
        sans: tokensV2.typography.family.sans.split(', '),
      },
      fontSize: {
        'xs': tokensV2.typography.size.xs,
        'sm': tokensV2.typography.size.sm,
        'base': tokensV2.typography.size.base,
        'lg': tokensV2.typography.size.lg,
        'xl': tokensV2.typography.size.xl,
        '2xl': tokensV2.typography.size['2xl'],
        '3xl': tokensV2.typography.size['3xl'],
        '4xl': tokensV2.typography.size['4xl'],
        '5xl': tokensV2.typography.size['5xl'],
      },
      lineHeight: {
        tight: tokensV2.typography.lineHeight.tight,
        normal: tokensV2.typography.lineHeight.normal,
        relaxed: tokensV2.typography.lineHeight.relaxed,
      },
      fontWeight: {
        normal: tokensV2.typography.fontWeight.normal,
        medium: tokensV2.typography.fontWeight.medium,
        semibold: tokensV2.typography.fontWeight.semibold,
        bold: tokensV2.typography.fontWeight.bold,
        extrabold: tokensV2.typography.fontWeight.extrabold,
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        dash: {
          '0%': { strokeDashoffset: '20' },
          '100%': { strokeDashoffset: '0' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.3s ease-in-out',
        slideUp: 'slideUp 0.3s ease-out',
        slideDown: 'slideDown 0.3s ease-out',
        scaleIn: 'scaleIn 0.2s ease-out',
        dash: 'dash 0.5s ease-in-out forwards',
        shimmer: 'shimmer 2s linear infinite',
      },
      backgroundImage: {
        'gradient-primary': tokensV2.gradients.primary,
        'gradient-primary-reverse': tokensV2.gradients.primaryReverse,
        'gradient-hero': tokensV2.gradients.hero,
        'gradient-subtle': tokensV2.gradients.subtle,
      },
    },
  },
  plugins: [],
};
